version: "3"
services:
  notebook:
    container_name: "learning-datascience-notebook"
    build: .
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
      - ./study:/home/jovyan/study
      - ./data:/home/jovyan/data
    command: start-notebook.sh --NotebookApp.token=''
